name: xaj-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - numba
  - pandas
  - scikit-learn
  - deap
  - spotpy=1.5.14
  - seaborn
  - tqdm
  - yaml
  - bmipy
  # for dev 
  - sphinx
  - pytest
  - black
  - flake8
  # pip
  - pip
  - pip:
    - setuptools
    - wheel
    - twine
    - bump2version
    - hydrodataset
